Fixed circular symlink infinte loop
mihneadb/node-directory-tree pull request #90
Opened 2021-07-30 01:53 UTC by airarrazaval

Fix for issue https://github.com/mihneadb/node-directory-tree/issues/89

Other improvements in this PR:

* Fixed indentation in `index.d.ts`
* Improved types definition
* Added ` isSymbolicLink`  property for DirectoryTree item and `followSymlinks` property in DirectoryTree options

2021-08-04 17:13 UTC, mihneadb requested changes
Thanks for this! 2 minor asks:
* please make sure to fix the indentation in the js file
* a test would be nice (can't remember if git supports symlinks or not?)

2021-08-04 17:13 UTC, mihneadb commented on lib/directory-tree.js
> +  options = options || {};
The indentation looks odd here.

2021-08-05 14:02 UTC, airarrazaval reviewed
I fixed the indentation by replacing tabs with spaces. Regarding symlink, git does support it.  I will have a look at it.

2021-08-06 20:13 UTC, airarrazaval commented
@mihneadb Tests successfully passing and included symlink

2021-08-12 13:01 UTC, mihneadb approved these changes
Great, thanks!

2021-08-12 13:01 UTC, merged

2021-08-12 17:04 UTC, mihneadb commented on index.d.ts
> +    attributes ? : (keyof directoryTree.Stats)[];
directoryTree.Stats is no longer a thing I guess. 😅 https://github.com/mihneadb/node-directory-tree/issues/91